package com.oracle.anc.fmwpoc.sf.model.views;

import com.oracle.anc.fmwpoc.sf.model.views.common.OpportunitiesView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 27 08:36:07 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OpportunitiesViewImpl extends ViewObjectImpl implements OpportunitiesView {
    /**
     * This is the default constructor (do not remove).
     */
    public OpportunitiesViewImpl() {
    }
    public void refreshAccountsLOV() {
        OpportunitiesViewRowImpl currentRow =
            (OpportunitiesViewRowImpl)this.getCurrentRow();
        currentRow.getLovModule_AccountsLovView1_1().executeQuery();
    }
}
