package com.oracle.anc.fmwpoc.sf.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 27 08:39:17 EET 2015
// ---------------------------------------------------------------------
public interface OpportunitiesView extends ViewObject {
    void refreshAccountsLOV();
}
